start:
    nix run &

stop:
    killall -q sketchybar || echo "No sketchybar processes running"

restart: stop start

status:
    ps aux | grep sketchybar | grep -v grep || echo "No sketchybar processes running"
