# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = [
  # 'exec-and-forget "open -a /Applications/WezTerm.app"'
]

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # Before starting everything up, kill dependent apps so they can refresh configs
    # ... this is killing things started below so no bueno...
    #'exec-and-forget killall -q sketchybar borders',

    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget BORDERSBIN active_color=0xff5EA994 inactive_color=0xff494d64 width=6.0',
    'exec-and-forget SKETCHYBARBIN -c NIXPATHTOSKETCHYCONFIG',
    'exec-and-forget SKETCHYBARBIN --trigger aerospace_started',
]
exec-on-workspace-change = ['/bin/bash', '-c',
  'SKETCHYBARBIN --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 50

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true


# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# cmd-alt-ctrl-enter = 'exec-and-forget kitty --single-instance -d ~'
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
cmd-alt-ctrl-enter = 'exec-and-forget /opt/homebrew/bin/kitty --single-instance -d ~'
cmd-alt-ctrl-f = 'fullscreen'
alt-s = 'layout floating tiling'
alt-e = 'balance-sizes'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-ctrl-alt-slash = 'layout tiles horizontal vertical'
cmd-ctrl-alt-alt-comma = 'layout accordion horizontal vertical'

cmd-alt-ctrl-q = 'workspace prev'
cmd-alt-ctrl-e = 'workspace next'


# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-l = 'focus right'

cmd-alt-ctrl-left = 'move left'
cmd-alt-ctrl-right = 'move right'
cmd-alt-ctrl-up = 'move up'
cmd-alt-ctrl-down = 'move down'

cmd-alt-ctrl-w = 'resize height +30'
cmd-alt-ctrl-s = 'resize height -30'
cmd-alt-ctrl-a = 'resize width +30'
cmd-alt-ctrl-d = 'resize width -30'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
ctrl-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
ctrl-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-cmd-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']


[[on-window-detected]]
if.app-id = "company.thebrowser.Browser"
run = "move-node-to-workspace 1"
[[on-window-detected]]
if.app-id = "net.kovidgoyal.kitty"
run = "move-node-to-workspace 2"
[[on-window-detected]]
if.app-id = "com.apple.finder"
run = "move-node-to-workspace 3"
[[on-window-detected]]
if.app-id = "com.microsoft.VSCode"
run = "move-node-to-workspace 4"
[[on-window-detected]]
if.app-id = "com.lukilabs.lukiapp"
run = "move-node-to-workspace 8"
[[on-window-detected]]
if.app-id = "dev.vencord.vesktop"
run = "move-node-to-workspace 9"
