import json
import os

from kitty.fast_data_types import Screen
from kitty.tab_bar import (
    DrawData,
    ExtraData,
    TabBarData,
    as_rgb,
    draw_title,
)

# --- Theme colors loaded from JSON (generated by Nix from theme.colors) ---
_COLORS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "theme_colors.json"
)
with open(_COLORS_PATH) as _f:
    _THEME = json.load(_f)


def theme(name: str) -> int:
    """Resolve a theme color name (e.g. "text") to a kitty as_rgb value."""
    return as_rgb(int(_THEME[name].lstrip("#"), 16))


# Leading logo glyph drawn once at the far left (BerkeleyMono Nerd Font).
ICON = ""
ICON_RIGHT_MARGIN = 0

# Separator drawn between tabs.
SEP = ""

# Per-tab icons keyed by tab index -> (active_glyph, inactive_glyph).
# Placeholders: swap in whatever Nerd Font glyphs you want per tab.
TAB_ICONS = {
    1: ("􀀻 ", "􀓞 "),
    2: ("􀀽 ", "􀓞 "),
    3: ("􀀿 ", "􀓞 "),
    4: ("􀁁 ", "􀓞 "),
    5: ("􀁃 ", "􀓞 "),
    6: ("􀁃 ", "􀓞 "),
    7: ("􀁇 ", "􀓞 "),
    8: ("􀁉 ", "􀓞 "),
    9: ("􀁋 ", "􀓞 "),
    10: ("􀔔 ", "􀓞 "),
}
# Fallback (active, inactive) for any index not listed above.
DEFAULT_TAB_ICON = ("􀝜 ", "􀓞 ")  # placeholder: filled / empty circle

icon_fg = theme("text")
icon_bg = theme("surface1")
bar_bg = theme("base")
sep_color = theme("overlay1")


def _draw_icon(screen: Screen, index: int) -> int:
    if index != 1:
        return 0

    fg, bg = screen.cursor.fg, screen.cursor.bg
    screen.cursor.fg = icon_fg
    screen.cursor.bg = icon_bg
    screen.draw(ICON)
    # Right margin, drawn on the bar background (not the tab background).
    screen.cursor.fg, screen.cursor.bg = fg, bar_bg
    screen.draw(" " * ICON_RIGHT_MARGIN)
    # Restore the tab's colors for the upcoming tab content.
    screen.cursor.bg = bg
    screen.cursor.x = len(ICON) + ICON_RIGHT_MARGIN
    return screen.cursor.x


def _draw_left_status(
    draw_data: DrawData,
    screen: Screen,
    tab: TabBarData,
    before: int,
    max_title_length: int,
    index: int,
    is_last: bool,
    extra_data: ExtraData,
) -> int:
    # Per-tab icon with 1-char padding on each side. The cursor's fg/bg are
    # already set by kitty to this tab's (active vs inactive) colors.
    active_icon, inactive_icon = TAB_ICONS.get(index, DEFAULT_TAB_ICON)
    icon = active_icon if tab.is_active else inactive_icon
    screen.draw(" " + icon + " ")

    draw_title(draw_data, screen, tab, index)
    screen.draw(" ")

    # Truncate the title to fit this tab's budget (see notes in the message).
    extra = screen.cursor.x - before - max_title_length
    if extra > 0:
        screen.cursor.x -= extra + 1
        screen.draw("…")

    end = screen.cursor.x
    screen.cursor.bold = screen.cursor.italic = False
    screen.cursor.fg = 0
    if not is_last:
        screen.cursor.fg = sep_color
        screen.cursor.bg = bar_bg
        screen.draw(SEP)
    screen.cursor.bg = 0
    return end


def draw_tab(
    draw_data: DrawData,
    screen: Screen,
    tab: TabBarData,
    before: int,
    max_title_length: int,
    index: int,
    is_last: bool,
    extra_data: ExtraData,
) -> int:
    _draw_icon(screen, index)
    _draw_left_status(
        draw_data,
        screen,
        tab,
        before,
        max_title_length,
        index,
        is_last,
        extra_data,
    )

    return screen.cursor.x
